// The characters of the MSBL Gear Builder snapshot, as its character panes show them: base stats
// (strength, speed, shooting, passing, technique) and speed with the ball. Extracted from the snapshot's
// pane files (see docs/msbl-gear-builder-snapshot.md); pane.ts renders them.

export interface GearCharacter {
  /** Pane file name and tab order (1..16). */
  readonly slug: string;
  readonly index: number;
  readonly name: string;
  /** Id of the build cell, e.g. "Ma". */
  readonly abbreviation: string;
  readonly cssClass: string;
  /** Card picture in assets/gear-builder/images/characters/. */
  readonly image: string;
  readonly cardName: string;
  readonly stats: readonly [number, number, number, number, number];
  readonly speedWithBall: string;
}

export const GEAR_CHARACTERS: readonly GearCharacter[] = [
  {
    slug: "mario",
    index: 1,
    name: "Mario",
    abbreviation: "Ma",
    cssClass: "mario",
    image: "Mario.png",
    cardName: "MARIO",
    stats: [11, 12, 14, 10, 16],
    speedWithBall: "6.3",
  },
  {
    slug: "luigi",
    index: 2,
    name: "Luigi",
    abbreviation: "Lu",
    cssClass: "luigi",
    image: "Luigi.png",
    cardName: "LUIGI",
    stats: [11, 11, 10, 14, 17],
    speedWithBall: "5.7",
  },
  {
    slug: "bowser",
    index: 3,
    name: "Bowser",
    abbreviation: "Bo",
    cssClass: "bowser",
    image: "Bowser.png",
    cardName: "BOWSER",
    stats: [17, 9, 17, 11, 9],
    speedWithBall: "2.5",
  },
  {
    slug: "peach",
    index: 4,
    name: "Peach",
    abbreviation: "Pe",
    cssClass: "peach",
    image: "Peach.png",
    cardName: "PEACH",
    stats: [9, 17, 9, 13, 15],
    speedWithBall: "10.0",
  },
  {
    slug: "rosalina",
    index: 5,
    name: "Rosalina",
    abbreviation: "Ro",
    cssClass: "rosalina",
    image: "Rosalina.png",
    cardName: "ROSALINA",
    stats: [14, 9, 17, 10, 13],
    speedWithBall: "3.3",
  },
  {
    slug: "toad",
    index: 6,
    name: "Toad",
    abbreviation: "To",
    cssClass: "toad",
    image: "Toad.png",
    cardName: "TOAD",
    stats: [9, 17, 11, 15, 11],
    speedWithBall: "9.2",
  },
  {
    slug: "yoshi",
    index: 7,
    name: "Yoshi",
    abbreviation: "Yo",
    cssClass: "yoshi",
    image: "Yoshi.png",
    cardName: "YOSHI",
    stats: [10, 10, 17, 17, 9],
    speedWithBall: "3.3",
  },
  {
    slug: "dk",
    index: 8,
    name: "DK",
    abbreviation: "DK",
    cssClass: "dk",
    image: "Donkey_Kong.png",
    cardName: "DK",
    stats: [16, 9, 13, 16, 9],
    speedWithBall: "2.5",
  },
  {
    slug: "wario",
    index: 9,
    name: "WARIO",
    abbreviation: "Wr",
    cssClass: "wario",
    image: "Wario.png",
    cardName: "WARIO",
    stats: [17, 9, 15, 13, 9],
    speedWithBall: "2.5",
  },
  {
    slug: "waluigi",
    index: 10,
    name: "Waluigi",
    abbreviation: "Wl",
    cssClass: "waluigi",
    image: "Waluigi.png",
    cardName: "WALUIGI",
    stats: [15, 16, 9, 9, 14],
    speedWithBall: "9.0",
  },
  {
    slug: "shy-guy",
    index: 11,
    name: "Shy&nbspGuy",
    abbreviation: "SG",
    cssClass: "shyguy",
    image: "Shy_Guy.png",
    cardName: "SHY GUY",
    stats: [13, 12, 13, 13, 12],
    speedWithBall: "5.5",
  },
  {
    slug: "daisy",
    index: 12,
    name: "Daisy",
    abbreviation: "Da",
    cssClass: "daisy",
    image: "Daisy.png",
    cardName: "DAISY",
    stats: [13, 9, 10, 13, 18],
    speedWithBall: "4.3",
  },
  {
    slug: "pauline",
    index: 13,
    name: "Pauline",
    abbreviation: "Pa",
    cssClass: "pauline",
    image: "Pauline.png",
    cardName: "PAULINE",
    stats: [20, 16, 9, 9, 9],
    speedWithBall: "8.0",
  },
  {
    slug: "diddy-kong",
    index: 14,
    name: "Diddy&nbspKong",
    abbreviation: "Di",
    cssClass: "diddykong",
    image: "Diddy_Kong.png",
    cardName: "DIDDY KONG",
    stats: [9, 16, 9, 16, 13],
    speedWithBall: "8.8",
  },
  {
    slug: "bowser-jr",
    index: 15,
    name: "Bowser&nbspJr",
    abbreviation: "BJ",
    cssClass: "bowserjr",
    image: "Bowser_Jr.png",
    cardName: "BOWSER JR",
    stats: [13, 13, 11, 17, 9],
    speedWithBall: "5.6",
  },
  {
    slug: "birdo",
    index: 16,
    name: "Birdo",
    abbreviation: "Bi",
    cssClass: "birdo",
    image: "Birdo.png",
    cardName: "BIRDO",
    stats: [9, 10, 18, 9, 17],
    speedWithBall: "4.9",
  },
];
