FROM alpine:3.22

RUN apk add --no-cache nginx nginx-mod-http-brotli \
    && mkdir -p /run/nginx /usr/share/nginx/html \
    && rm -f /etc/nginx/http.d/default.conf

WORKDIR /usr/share/nginx/html

COPY index.html robots.txt sitemap.xml ./
COPY assets ./assets
COPY css ./css
COPY js ./js
COPY pages ./pages
COPY nginx/frontend.conf /etc/nginx/http.d/default.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
