// Writes infra/nginx/generated/legacy-routes.conf from the shared route data, so nginx and
// resolveRoute() cannot drift apart. `--check` fails instead of writing when the file is stale.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { LEGACY_REDIRECTS, LEGACY_SUBMENU_ROUTES, RETIRED_PATHS } from "@ms/shared/site/legacy-routes";
import { pageFile } from "@ms/shared/site/routes";
import { REPO_ROOT } from "./processes.ts";

const OUTPUT = join(REPO_ROOT, "infra", "nginx", "generated", "legacy-routes.conf");
const PAGE_CACHE = 'add_header Cache-Control "public, max-age=300, must-revalidate" always;';

export function renderLegacyRoutes(): string {
  const lines = [
    "# Generated by tools/src/generate-nginx-routes.ts from packages/shared/src/site/legacy-routes.ts.",
    "# Do not edit; run `npm run generate:nginx` after changing the shared route data.",
    "",
    "# Old URLs of existing pages.",
  ];
  for (const [path, slug] of Object.entries(LEGACY_REDIRECTS)) {
    lines.push(`location = ${path} {`, `    return 301 /${slug}$is_args$args;`, "}");
  }
  lines.push("", "# Retired pages.");
  for (const path of RETIRED_PATHS) lines.push(`location = ${path} {`, "    return 404;", "}");
  lines.push("", "# Overview pages that used to switch content with ?submenu=.");
  for (const [section, routes] of Object.entries(LEGACY_SUBMENU_ROUTES)) {
    lines.push(`location = /${section} {`);
    for (const [submenu, slug] of Object.entries(routes)) {
      lines.push(`    if ($arg_submenu = ${submenu}) {`, `        return 301 /${slug}$is_args$args;`, "    }");
    }
    lines.push(`    ${PAGE_CACHE}`, `    try_files ${pageFile(section)} =404;`, "}");
  }
  return lines.join("\n") + "\n";
}

if (import.meta.main) {
  const expected = renderLegacyRoutes();
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(OUTPUT, "utf8");
    } catch {
      // Missing counts as stale.
    }
    if (current !== expected) {
      console.error(`${OUTPUT} is out of date; run npm run generate:nginx.`);
      process.exit(1);
    }
    console.log("[nginx] Generated routes are up to date.");
  } else {
    mkdirSync(dirname(OUTPUT), { recursive: true });
    writeFileSync(OUTPUT, expected);
    console.log(`[nginx] Wrote ${OUTPUT}`);
  }
}
